
logging:
    level:
        org:
            hibernate:
                SQL: off
                type:
                    descriptor:
                        sql:
                            BasicBinder: off
            springframework:
                web:
                    DEBUG
                jdbc:
                    core:
                        JdbcTemplate: off
                        StatementCreatorUtils: off
spring:
    datasource:
        driverClassName: org.h2.Driver
        password: 123
        url: jdbc:h2:mem:restdb
        username: emad
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        properties:
            hibernate:
                format_sql: true
                hbm2ddl:
                    auto: create-drop
                show_sql: false
server:
    servlet:
        context-path: /api
    port: 8081
